Repository Room-Elephant/extension-chrome-key-retriever, pull requests merged in 2023-07, with the labels that each got.

#1 feat: add set key behaviour
  README.md
  docs/preview.png
  items.js
  keyReader.js
  keyWriter.js
  manager.js
  popup.html
  popup.js
Labels: enhancement

#20 feat: add listener to store
  src/handler/store.js
  src/popup.js
Labels: enhancement

#21 refactor: do code refactor - part2
  src/handler/store.js
  src/items.js
  src/manager.js
  src/page.js
  src/popup.html
  src/popup.js
Labels: enhancement

#22 chore: refactor items and clean css
  src/components.js
  src/items.js
  src/page.js
  src/popup.css
  src/popup.html
Labels: enhancement

#23 chore: change cookie icon
  src/items.js
  src/popup.html
Labels: enhancement

#24 chore: update btn toggle color
  src/components.js
  src/items.js
  src/popup.css
Labels: enhancement

#25 chore: move storage type selection to top in add key form
  src/components.js
  src/items.js
  src/popup.html
Labels: enhancement

#26 feat: add cancel btn to apply key footer
  src/components.js
  src/items.js
Labels: enhancement

#27 feat: add validation to add key form
  src/page.js
  src/popup.css
  src/popup.html
Labels: enhancement

#28 feat: add empty page
  README.md
  images/empty-page.jpg
  src/components.js
  src/page.js
  src/popup.css
  src/popup.html
  src/popup.js
Labels: enhancement

#38 fix: fix min height in section
  src/popup.html
Labels: enhancement

#41 feat: add google analytics config
  .eslintrc.json
  src/handler/analytics.js
  src/handler/versionController.js
  src/page.js
  src/popup.html
  src/popup.js
Labels: enhancement

#43 fix: remove placeholders and add required flag to labels
  src/popup.css
  src/popup.html
Labels: bug

#48 fix delete action
  src/handler/store.js
Labels: bug, minor

#49 feat: add refresh button
  src/page.js
  src/popup.html
  src/popup.js
Labels: enhancement, major

#54 fix: fix scroll to section
  src/popup.css
  src/popup.html
Labels: bug

#52 feat: add key and subkey to view/set token area
  .eslintrc.json
  src/common.js
  src/components.js
  src/items.js
  src/page.js
  src/popup.css
Labels: enhancement, major, need adjustments

#62 feat: migrate to ES6 modules
  .eslintrc.json
  .github/workflows/ci.yml
  CODE_OF_CONDUCT.md
  README.md
  package.json
  src/common.js
  src/components.js
  src/handler/analytics.js
  src/handler/operation/cookie.js
  src/handler/operation/remote.js
  src/handler/store.js
  src/handler/valueReader.js
  src/handler/valueWriter.js
  src/handler/versionController.js
  src/items.js
  src/manager.js
  src/page.js
  src/popup.html
  src/popup.js
  src/view/components.js
  src/view/items.js
Labels: enhancement, major

#69 feat: add build with webpack
  .eslintignore
  .gitignore
  .prettierignore
  package.json
  webpack.config.js
Labels: enhancement, major

#67 feat: retrieve key from lambda
  src/handler/analytics.js
Labels: enhancement, minor

#81 feat: Focus on set value
  src/view/items.js
Labels: enhancement, minor

#83 update readme
  README.md
  manifest.json
  package.json
Labels: enhancement, minor
